#!/bin/bash

IMG=${1:-}

if [ -z "$IMG" ]
then
	IMGPATH=/Users/julianlioanag/wallpapers
	wal --backend colorz -i $IMGPATH
	neofetch
else
	IMGPATH=/Users/julianlioanag/wallpapers/$IMG
	wal --backend colorz -i $IMGPATH
	neofetch --iterm2 $IMGPATH
fi

#open -a iTerm .
#pipes.sh -t 0
